DELETE http://localhost:3250/logout
content-type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiJ9.d2FybmVy.2542rYPKGRkf1pmPYtnP281JyxCHPx8oCiP8rIgz8IQ"
}
###
POST http://localhost:3250/token
content-type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiJ9.d2FybmVy.2542rYPKGRkf1pmPYtnP281JyxCHPx8oCiP8rIgz8IQ"
}

###
POST http://localhost:3250/login
content-type: application/json

{
    "username": "warner"
}


